version: '3'
services:
  geth:
    image: ethereum/client-go:latest
    container_name: geth
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - /home/femiadebimpe/.eth:/home/femiadebimpe/.ethereum
    stop_signal: SIGINT
    stop_grace_period: 2m
    command:
      - --goerli
      - --syncmode=snap
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --ws
      - --ws.port=8546
      - --ws.addr=0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
